"""Phase 11C.1C-A - Adaptive Candidate Regime & Strategy Selector contracts.

This package ships the *first version* of the data contracts the
Phase 11C.1B WebSocket-first all-market radar consumes to:

  - assess the current market regime
  - classify a candidate's life-cycle stage
    (early / mid / late / blowoff / dumped)
  - score a candidate opportunity (S / A / B / C)
  - choose a paper-only strategy expression
    (follow / pullback / observe / reject)
  - record a cluster context (peer leader, peer rank)
  - enqueue future MFE / MAE / Tail-label tracking windows

Phase 11C.1C-A boundary
-----------------------

Every object in this package is a frozen value object or a pure
function. Nothing here:

  - opens a socket
  - imports an exchange SDK / LLM client / Telegram library
  - reads ``os.environ`` for credentials
  - mutates global state
  - calls ``EventRepository.append_event`` directly
  - constructs a real :class:`OrderRequest` / :class:`OrderIntent`
  - flips a Phase 1 safety flag
  - implements a full MFE / MAE processor (the contract is a
    *queue*, not a runner)
  - implements AI Learning (the contract is a *paper plan*, not
    a trade authority)
  - opens a path into Phase 12

The strategy_mode decision below is a **paper / virtual** field.
It records what the strategy expression *would* be if (and only if)
every Phase 1-11C invariant agrees. It does NOT and CANNOT trigger
a real trade; the Risk Engine remains the single trade-decision
gate.

Public surface
--------------

    MarketRegimeAssessment        macro-cycle assessment + risk multiplier
    CandidateStageAssessment      early / mid / late / blowoff / dumped
    OpportunityScore              weighted-sum score + S/A/B/C grade
    StrategyModeDecision          follow / pullback / observe / reject
    ClusterContext                cluster_id + leader + rank
    LabelQueueContract            future MFE/MAE/Tail label queue
    AdaptiveCandidateContext      aggregator bundle for one candidate

    AdaptiveStrategyVersion       canonical version label for this PR
    AdaptiveScoringVersion        scoring-formula version label
    AdaptiveStateMachineVersion   adaptive-state-machine version label

    assess_market_regime          cheap deterministic regime classifier
    classify_candidate_stage      stage classifier (5 buckets)
    compute_opportunity_score     score + grade
    select_strategy_mode          follow / pullback / observe / reject
    build_cluster_context         peer-cluster builder
    build_label_queue_contract    label-queue contract builder
    build_adaptive_candidate_context  one-shot orchestrator

The :func:`build_adaptive_candidate_context` helper is the single
entry point the Phase 11C.1B WS-radar event-chain driver calls per
ACTIVE candidate.
"""

from app.adaptive.cluster import build_cluster_context
from app.adaptive.context import (
    ADAPTIVE_LEARNING_READY_KEY,
    AdaptiveScoringVersion,
    AdaptiveStateMachineVersion,
    AdaptiveStrategyVersion,
    build_adaptive_candidate_context,
)
from app.adaptive.label_queue import (
    DEFAULT_TRACKING_WINDOWS,
    build_label_queue_contract,
)
from app.adaptive.label_runtime import (
    DEFAULT_PRIMARY_WINDOW,
    DEFAULT_TRACKING_WINDOW_SECONDS,
    KNOWN_LABEL_TRACKING_SCHEMA_VERSIONS,
    LABEL_TRACKING_SCHEMA_VERSION,
    LABEL_TRACKING_STATUSES,
    LabelQueueRuntime,
    LabelQueueRuntimeConfig,
    LabelTrackingRecord,
    TAIL_LABELS,
    TrackingWindowState,
    assign_tail_label_for_window,
    compute_pct_return,
    update_window_with_price,
)
from app.adaptive.models import (
    AdaptiveCandidateContext,
    CANDIDATE_STAGES,
    CandidateStageAssessment,
    ClusterContext,
    LabelQueueContract,
    MarketRegimeAssessment,
    OPPORTUNITY_GRADES,
    OPPORTUNITY_GRADE_BOUNDARIES,
    OpportunityScore,
    REGIME_BUCKETS,
    RuntimeCalibrationMetrics,
    STRATEGY_MODES,
    StrategyModeDecision,
    candidate_stage_assessment_to_payload,
    cluster_context_to_payload,
    label_queue_contract_to_payload,
    market_regime_assessment_to_payload,
    opportunity_score_to_payload,
    runtime_calibration_metrics_to_payload,
    strategy_mode_decision_to_payload,
)
from app.adaptive.regime import assess_market_regime
from app.adaptive.runtime import (
    DEFAULT_EARLY_TAIL_PROTECT_THRESHOLD,
    DEFAULT_FRESHNESS_HALF_LIFE_MS,
    compute_early_tail_score,
    compute_freshness_score,
    compute_late_chase_risk_score,
    compute_relative_acceleration,
    compute_runtime_calibration,
)
from app.adaptive.scoring import (
    DEFAULT_OPPORTUNITY_SCORE_WEIGHTS,
    OpportunityScoreInputs,
    OpportunityScoreWeights,
    compute_opportunity_score,
    grade_for_score,
)
from app.adaptive.selector import select_strategy_mode
from app.adaptive.stage import classify_candidate_stage
from app.adaptive.strategy_validation import (
    CLUSTER_ACTIONS,
    DEFAULT_OVEREXPOSURE_WARNING_THRESHOLD,
    EARLY_TAIL_SCORE_BUCKETS,
    EARLY_TAIL_SCORE_BUCKET_LABELS,
    KNOWN_STRATEGY_VALIDATION_SCHEMA_VERSIONS,
    OPPORTUNITY_SCORE_BUCKETS,
    OPPORTUNITY_SCORE_BUCKET_LABELS,
    STRATEGY_VALIDATION_PRIMARY_WINDOW,
    STRATEGY_VALIDATION_SCHEMA_VERSION,
    STRATEGY_VALIDATION_SOURCE_PHASE,
    STRATEGY_VALIDATION_TRACKING_WINDOWS,
    STRATEGY_VALIDATION_VERSION,
    CandidateStageValidationStats,
    ClusterExposureAssessment,
    ClusterLeaderValidationStats,
    EarlyTailScoreBucketStats,
    OpportunityScoreBucketStats,
    StrategyModeValidationStats,
    StrategyValidationReport,
    StrategyValidationSample,
    StrategyValidationWindowStats,
    TailLabelDistribution,
    aggregate_by_candidate_stage,
    aggregate_by_early_tail_score_bucket,
    aggregate_by_opportunity_score_bucket,
    aggregate_by_strategy_mode,
    aggregate_tail_label_distribution,
    assess_cluster_exposure,
    build_strategy_validation_report,
    build_strategy_validation_sample,
    early_tail_score_bucket_for,
    evaluate_cluster_leader_performance,
    opportunity_score_bucket_for,
)
from app.adaptive.strategy_validation_runtime import (
    StrategyValidationRuntime,
    StrategyValidationRuntimeConfig,
)
from app.adaptive.strategy_validation_dataset import (
    CANONICAL_CANDIDATE_STAGES,
    CANONICAL_STRATEGY_MODES,
    COMPLETED_TAIL_LABELS,
    KNOWN_STRATEGY_VALIDATION_DATASET_SCHEMA_VERSIONS,
    QUALITY_GATE_STATUSES,
    REQUIRED_DATASET_RECORD_FIELDS,
    STRATEGY_VALIDATION_DATASET_SCHEMA_VERSION,
    STRATEGY_VALIDATION_DATASET_SOURCE_PHASE,
    STRATEGY_VALIDATION_DATASET_VERSION,
    StrategyValidationDataset,
    StrategyValidationDatasetRecord,
    StrategyValidationDatasetSummary,
    StrategyValidationQualityGate,
    StrategyValidationQualityGateResult,
    build_validation_dataset_from_samples,
    evaluate_validation_dataset_quality,
    export_validation_dataset_payload,
    load_validation_dataset_payload,
    summarize_validation_dataset,
)
from app.adaptive.paper_alpha_gate import (
    DEFAULT_FOLLOW_FAKE_BREAKOUT_RATE,
    DEFAULT_HIGH_BUCKET_ADVANTAGE,
    DEFAULT_LATE_CHASE_FAKE_BREAKOUT_RATE,
    DEFAULT_LEADER_PREFERENCE_ADVANTAGE,
    DEFAULT_MIN_BUCKET_SAMPLES,
    DEFAULT_MIN_COMPLETED_TAIL_LABELS,
    DEFAULT_MIN_TOTAL_SAMPLES,
    DEFAULT_MISSED_ALPHA_STRONG_TAIL_RATE,
    HIGH_EARLY_TAIL_SCORE_BUCKETS,
    HIGH_OPPORTUNITY_SCORE_BUCKETS,
    KNOWN_PAPER_ALPHA_GATE_SCHEMA_VERSIONS,
    LOW_EARLY_TAIL_SCORE_BUCKETS,
    LOW_OPPORTUNITY_SCORE_BUCKETS,
    PAPER_ALPHA_COHORT_DIMENSIONS,
    PAPER_ALPHA_GATE_SCHEMA_VERSION,
    PAPER_ALPHA_GATE_SOURCE_PHASE,
    PAPER_ALPHA_GATE_STATUSES,
    PAPER_ALPHA_GATE_VERSION,
    PaperAlphaGateCohortResult,
    PaperAlphaGateInput,
    PaperAlphaGateReport,
    PaperAlphaGateRule,
    PaperAlphaGateRuleResult,
    PaperAlphaGateStatus,
    build_paper_alpha_gate_input,
    build_paper_alpha_gate_report,
    evaluate_candidate_stage_alpha,
    evaluate_cluster_alpha,
    evaluate_paper_alpha_gate,
    evaluate_score_bucket_alpha,
    evaluate_strategy_mode_alpha,
    export_paper_alpha_gate_payload,
    load_paper_alpha_gate_payload,
)
from app.adaptive.post_discovery_outcome_metrics import (
    DEFAULT_CHOPPY_DRAWDOWN_PCT,
    DEFAULT_CHOPPY_MAE_MFE_RATIO,
    DEFAULT_EARLY_REMAINING_UPSIDE_PCT,
    DEFAULT_FAKE_BREAKOUT_GIVEBACK_RATIO,
    DEFAULT_LATE_REMAINING_UPSIDE_PCT,
    DEFAULT_MIN_PRICE_PATH_POINTS,
    DEFAULT_MISSED_STRONG_TAIL_PCT,
    DEFAULT_TOO_LATE_REMAINING_UPSIDE_PCT,
    KNOWN_POST_DISCOVERY_OUTCOME_METRICS_SCHEMA_VERSIONS,
    POST_DISCOVERY_OUTCOME_FORBIDDEN_PAYLOAD_KEYS,
    POST_DISCOVERY_OUTCOME_METRICS_SCHEMA_VERSION,
    POST_DISCOVERY_OUTCOME_METRICS_SOURCE_PHASE,
    POST_DISCOVERY_OUTCOME_METRICS_VERSION,
    CaptureStatus as PostDiscoveryCaptureStatus,
    DetectionTimingLabel,
    HistoricalMoverReferenceSummary,
    OutcomeLabel,
    PostDiscoveryOutcomeEvaluator,
    PostDiscoveryOutcomeEvaluatorConfig,
    PostDiscoveryOutcomeForbiddenFieldError,
    PostDiscoveryOutcomeInput,
    PostDiscoveryOutcomeRecord,
    PostDiscoveryOutcomeReport,
    PricePoint,
    assert_payload_has_no_forbidden_keys as assert_post_discovery_payload_has_no_forbidden_keys,
    build_post_discovery_outcome_report,
)
from app.adaptive.reject_to_outcome_attribution import (
    DEFAULT_FALSE_NEGATIVE_MFE_THRESHOLD,
    DEFAULT_STRONG_REMAINING_UPSIDE_PCT,
    KNOWN_REJECT_TO_OUTCOME_ATTRIBUTION_SCHEMA_VERSIONS,
    REJECT_ATTRIBUTION_FORBIDDEN_PAYLOAD_KEYS,
    REJECT_TO_OUTCOME_ATTRIBUTION_SCHEMA_VERSION,
    REJECT_TO_OUTCOME_ATTRIBUTION_SOURCE_PHASE,
    REJECT_TO_OUTCOME_ATTRIBUTION_VERSION,
    RejectAttributionEngineConfig,
    RejectAttributionForbiddenFieldError,
    RejectAttributionInput,
    RejectAttributionRecord,
    RejectAttributionReport,
    RejectAttributionVerdict,
    RejectToOutcomeAttributionEngine,
    assert_payload_has_no_forbidden_keys as assert_reject_attribution_payload_has_no_forbidden_keys,
    build_reject_attribution_report,
)
from app.adaptive.severe_missed_tail_triage import (
    DEFAULT_TRUE_DISCOVERY_FAILURE_MFE_THRESHOLD,
    FALSE_NEGATIVE_REJECT_ATTRIBUTION_VERDICT,
    KNOWN_SEVERE_MISSED_TAIL_TRIAGE_SCHEMA_VERSIONS,
    PROTECTIVE_REJECT_ATTRIBUTION_VERDICTS,
    ROOT_CAUSE_DEFAULT_SEVERITY,
    SEVERE_MISSED_TAIL_TRIAGE_FORBIDDEN_PAYLOAD_KEYS,
    SEVERE_MISSED_TAIL_TRIAGE_SCHEMA_VERSION,
    SEVERE_MISSED_TAIL_TRIAGE_SOURCE_PHASE,
    SEVERE_MISSED_TAIL_TRIAGE_VERSION,
    STRATEGY_MODE_FALSE_NEGATIVE_VERDICT,
    SevereMissedTailTriageEngine,
    SevereMissedTailTriageEngineConfig,
    SevereMissedTailTriageForbiddenFieldError,
    SevereMissRootCause,
    SevereMissSeverity,
    SevereMissTriageInput,
    SevereMissTriageRecord,
    SevereMissTriageReport,
    assert_payload_has_no_forbidden_keys as assert_severe_missed_tail_triage_payload_has_no_forbidden_keys,
    build_severe_missed_tail_triage_report,
)
from app.adaptive.discovery_quality_scorecard import (
    DEFAULT_DATA_GAP_RATE_DEGRADED,
    DEFAULT_DATA_GAP_RATE_WARN,
    DEFAULT_FALSE_NEGATIVE_REJECT_RATE_WARN,
    DEFAULT_GOOD_COVERAGE_RATE,
    DEFAULT_GOOD_USABLE_DISCOVERY_RATE,
    DEFAULT_INSUFFICIENT_PRICE_PATH_RATE_DEGRADED,
    DEFAULT_INSUFFICIENT_PRICE_PATH_RATE_WARN,
    DEFAULT_LATE_CHASE_RATE_WARN,
    DEFAULT_PARTIAL_COVERAGE_RATE,
    DEFAULT_PARTIAL_USABLE_DISCOVERY_RATE,
    DEFAULT_SEVERE_MISS_RATE_DEGRADED,
    DEFAULT_SEVERE_MISS_RATE_WARN,
    DISCOVERY_QUALITY_SCORECARD_FORBIDDEN_PAYLOAD_KEYS,
    DISCOVERY_QUALITY_SCORECARD_SCHEMA_VERSION,
    DISCOVERY_QUALITY_SCORECARD_SOURCE_PHASE,
    DISCOVERY_QUALITY_SCORECARD_VERSION,
    KNOWN_DISCOVERY_QUALITY_SCORECARD_SCHEMA_VERSIONS,
    DiscoveryQualityBucket,
    DiscoveryQualityScorecard,
    DiscoveryQualityScorecardEngine,
    DiscoveryQualityScorecardEngineConfig,
    DiscoveryQualityScorecardForbiddenFieldError,
    DiscoveryQualityScorecardInput,
    assert_payload_has_no_forbidden_keys as assert_discovery_quality_scorecard_payload_has_no_forbidden_keys,
    build_discovery_quality_scorecard,
)
from app.adaptive.regime_cluster_evidence_pack import (
    DEFAULT_FAKE_BREAKOUT_WARNING_RATE,
    DEFAULT_LATE_CHASE_FAILURE_WARNING_RATE,
    DEFAULT_MIN_COHORT_SAMPLES,
    DEFAULT_MISSED_TAIL_WARNING_RATE,
    DEFAULT_REACHED_3R_SIGNAL_RATE,
    DEFAULT_REACHED_5R_SIGNAL_RATE,
    DEFAULT_STRONG_TAIL_SIGNAL_RATE,
    KNOWN_REGIME_CLUSTER_EVIDENCE_SCHEMA_VERSIONS,
    REGIME_CLUSTER_COHORT_DIMENSIONS,
    REGIME_CLUSTER_EVIDENCE_PACK_STATUSES,
    REGIME_CLUSTER_EVIDENCE_SCHEMA_VERSION,
    REGIME_CLUSTER_EVIDENCE_SOURCE_PHASE,
    REGIME_CLUSTER_EVIDENCE_VERSION,
    UNKNOWN_CLUSTER,
    UNKNOWN_REGIME,
    ClusterCohortSummary,
    RegimeClusterCohortKey,
    RegimeClusterCohortStats,
    RegimeClusterEvidenceInput,
    RegimeClusterEvidencePack,
    RegimeClusterEvidencePackStatus,
    RegimeClusterEvidenceRecord,
    RegimeCohortSummary,
    ScoreBucketSummary,
    StageOutcomeSummary,
    StrategyModeOutcomeSummary,
    build_cluster_cohort_summary,
    build_regime_cluster_evidence_input,
    build_regime_cluster_evidence_pack,
    build_regime_cohort_summary,
    build_score_bucket_summary,
    build_stage_outcome_summary,
    build_strategy_mode_outcome_summary,
    export_regime_cluster_evidence_payload,
    load_regime_cluster_evidence_payload,
)

__all__ = [
    # Models / value objects
    "MarketRegimeAssessment",
    "CandidateStageAssessment",
    "OpportunityScore",
    "StrategyModeDecision",
    "ClusterContext",
    "LabelQueueContract",
    "RuntimeCalibrationMetrics",
    "AdaptiveCandidateContext",
    # Constants
    "ADAPTIVE_LEARNING_READY_KEY",
    "CANDIDATE_STAGES",
    "DEFAULT_EARLY_TAIL_PROTECT_THRESHOLD",
    "DEFAULT_FRESHNESS_HALF_LIFE_MS",
    "DEFAULT_TRACKING_WINDOWS",
    "DEFAULT_PRIMARY_WINDOW",
    "DEFAULT_TRACKING_WINDOW_SECONDS",
    "KNOWN_LABEL_TRACKING_SCHEMA_VERSIONS",
    "LABEL_TRACKING_SCHEMA_VERSION",
    "LABEL_TRACKING_STATUSES",
    "TAIL_LABELS",
    "OPPORTUNITY_GRADES",
    "OPPORTUNITY_GRADE_BOUNDARIES",
    "REGIME_BUCKETS",
    "STRATEGY_MODES",
    # Versions
    "AdaptiveStrategyVersion",
    "AdaptiveScoringVersion",
    "AdaptiveStateMachineVersion",
    # Pure functions
    "assess_market_regime",
    "classify_candidate_stage",
    "compute_opportunity_score",
    "compute_early_tail_score",
    "compute_freshness_score",
    "compute_late_chase_risk_score",
    "compute_relative_acceleration",
    "compute_runtime_calibration",
    "grade_for_score",
    "select_strategy_mode",
    "build_cluster_context",
    "build_label_queue_contract",
    "build_adaptive_candidate_context",
    # Phase 11C.1C-C-A label-tracking runtime
    "LabelQueueRuntime",
    "LabelQueueRuntimeConfig",
    "LabelTrackingRecord",
    "TrackingWindowState",
    "assign_tail_label_for_window",
    "compute_pct_return",
    "update_window_with_price",
    # Phase 11C.1C-C-B-A Strategy Validation Lab v0 + Cluster
    # Exposure Control Contracts
    "STRATEGY_VALIDATION_SCHEMA_VERSION",
    "STRATEGY_VALIDATION_VERSION",
    "STRATEGY_VALIDATION_SOURCE_PHASE",
    "STRATEGY_VALIDATION_PRIMARY_WINDOW",
    "STRATEGY_VALIDATION_TRACKING_WINDOWS",
    "KNOWN_STRATEGY_VALIDATION_SCHEMA_VERSIONS",
    "OPPORTUNITY_SCORE_BUCKETS",
    "OPPORTUNITY_SCORE_BUCKET_LABELS",
    "EARLY_TAIL_SCORE_BUCKETS",
    "EARLY_TAIL_SCORE_BUCKET_LABELS",
    "CLUSTER_ACTIONS",
    "DEFAULT_OVEREXPOSURE_WARNING_THRESHOLD",
    "StrategyValidationSample",
    "StrategyValidationWindowStats",
    "StrategyModeValidationStats",
    "CandidateStageValidationStats",
    "OpportunityScoreBucketStats",
    "EarlyTailScoreBucketStats",
    "TailLabelDistribution",
    "ClusterLeaderValidationStats",
    "ClusterExposureAssessment",
    "StrategyValidationReport",
    "build_strategy_validation_sample",
    "aggregate_by_strategy_mode",
    "aggregate_by_candidate_stage",
    "aggregate_by_opportunity_score_bucket",
    "aggregate_by_early_tail_score_bucket",
    "aggregate_tail_label_distribution",
    "evaluate_cluster_leader_performance",
    "assess_cluster_exposure",
    "build_strategy_validation_report",
    "opportunity_score_bucket_for",
    "early_tail_score_bucket_for",
    "StrategyValidationRuntime",
    "StrategyValidationRuntimeConfig",
    # Phase 11C.1C-C-B-B-A Strategy Validation Dataset Builder &
    # Quality Gate v0
    "STRATEGY_VALIDATION_DATASET_SCHEMA_VERSION",
    "STRATEGY_VALIDATION_DATASET_VERSION",
    "STRATEGY_VALIDATION_DATASET_SOURCE_PHASE",
    "KNOWN_STRATEGY_VALIDATION_DATASET_SCHEMA_VERSIONS",
    "QUALITY_GATE_STATUSES",
    "CANONICAL_STRATEGY_MODES",
    "CANONICAL_CANDIDATE_STAGES",
    "COMPLETED_TAIL_LABELS",
    "REQUIRED_DATASET_RECORD_FIELDS",
    "StrategyValidationDatasetRecord",
    "StrategyValidationDatasetSummary",
    "StrategyValidationDataset",
    "StrategyValidationQualityGate",
    "StrategyValidationQualityGateResult",
    "build_validation_dataset_from_samples",
    "summarize_validation_dataset",
    "evaluate_validation_dataset_quality",
    "export_validation_dataset_payload",
    "load_validation_dataset_payload",
    # Phase 11C.1C-C-B-B-B-A Paper Alpha Gate v0
    "PAPER_ALPHA_GATE_SCHEMA_VERSION",
    "KNOWN_PAPER_ALPHA_GATE_SCHEMA_VERSIONS",
    "PAPER_ALPHA_GATE_VERSION",
    "PAPER_ALPHA_GATE_SOURCE_PHASE",
    "PAPER_ALPHA_GATE_STATUSES",
    "PAPER_ALPHA_COHORT_DIMENSIONS",
    "DEFAULT_MIN_TOTAL_SAMPLES",
    "DEFAULT_MIN_COMPLETED_TAIL_LABELS",
    "DEFAULT_MIN_BUCKET_SAMPLES",
    "DEFAULT_HIGH_BUCKET_ADVANTAGE",
    "DEFAULT_LATE_CHASE_FAKE_BREAKOUT_RATE",
    "DEFAULT_MISSED_ALPHA_STRONG_TAIL_RATE",
    "DEFAULT_FOLLOW_FAKE_BREAKOUT_RATE",
    "DEFAULT_LEADER_PREFERENCE_ADVANTAGE",
    "HIGH_OPPORTUNITY_SCORE_BUCKETS",
    "LOW_OPPORTUNITY_SCORE_BUCKETS",
    "HIGH_EARLY_TAIL_SCORE_BUCKETS",
    "LOW_EARLY_TAIL_SCORE_BUCKETS",
    "PaperAlphaGateStatus",
    "PaperAlphaGateRule",
    "PaperAlphaGateRuleResult",
    "PaperAlphaGateCohortResult",
    "PaperAlphaGateInput",
    "PaperAlphaGateReport",
    "build_paper_alpha_gate_input",
    "evaluate_paper_alpha_gate",
    "evaluate_strategy_mode_alpha",
    "evaluate_candidate_stage_alpha",
    "evaluate_score_bucket_alpha",
    "evaluate_cluster_alpha",
    "build_paper_alpha_gate_report",
    "export_paper_alpha_gate_payload",
    "load_paper_alpha_gate_payload",
    # Phase 11C.1C-C-B-B-B-B Regime & Cluster Cohort Evidence Pack v0
    "REGIME_CLUSTER_EVIDENCE_SCHEMA_VERSION",
    "REGIME_CLUSTER_EVIDENCE_VERSION",
    "REGIME_CLUSTER_EVIDENCE_SOURCE_PHASE",
    "KNOWN_REGIME_CLUSTER_EVIDENCE_SCHEMA_VERSIONS",
    "REGIME_CLUSTER_COHORT_DIMENSIONS",
    "REGIME_CLUSTER_EVIDENCE_PACK_STATUSES",
    "UNKNOWN_REGIME",
    "UNKNOWN_CLUSTER",
    "DEFAULT_MIN_COHORT_SAMPLES",
    "DEFAULT_STRONG_TAIL_SIGNAL_RATE",
    "DEFAULT_REACHED_3R_SIGNAL_RATE",
    "DEFAULT_REACHED_5R_SIGNAL_RATE",
    "DEFAULT_FAKE_BREAKOUT_WARNING_RATE",
    "DEFAULT_MISSED_TAIL_WARNING_RATE",
    "DEFAULT_LATE_CHASE_FAILURE_WARNING_RATE",
    "RegimeClusterEvidencePackStatus",
    "RegimeClusterCohortKey",
    "RegimeClusterCohortStats",
    "RegimeClusterEvidenceRecord",
    "RegimeClusterEvidenceInput",
    "RegimeCohortSummary",
    "ClusterCohortSummary",
    "ScoreBucketSummary",
    "StageOutcomeSummary",
    "StrategyModeOutcomeSummary",
    "RegimeClusterEvidencePack",
    "build_regime_cluster_evidence_input",
    "build_regime_cohort_summary",
    "build_cluster_cohort_summary",
    "build_score_bucket_summary",
    "build_stage_outcome_summary",
    "build_strategy_mode_outcome_summary",
    "build_regime_cluster_evidence_pack",
    "export_regime_cluster_evidence_payload",
    "load_regime_cluster_evidence_payload",
    # Phase 11C.1C-C-B-B-B-D-B Post-Discovery Outcome Metrics v0
    "POST_DISCOVERY_OUTCOME_METRICS_SCHEMA_VERSION",
    "POST_DISCOVERY_OUTCOME_METRICS_VERSION",
    "POST_DISCOVERY_OUTCOME_METRICS_SOURCE_PHASE",
    "KNOWN_POST_DISCOVERY_OUTCOME_METRICS_SCHEMA_VERSIONS",
    "POST_DISCOVERY_OUTCOME_FORBIDDEN_PAYLOAD_KEYS",
    "DEFAULT_MIN_PRICE_PATH_POINTS",
    "DEFAULT_EARLY_REMAINING_UPSIDE_PCT",
    "DEFAULT_LATE_REMAINING_UPSIDE_PCT",
    "DEFAULT_TOO_LATE_REMAINING_UPSIDE_PCT",
    "DEFAULT_CHOPPY_MAE_MFE_RATIO",
    "DEFAULT_CHOPPY_DRAWDOWN_PCT",
    "DEFAULT_MISSED_STRONG_TAIL_PCT",
    "DEFAULT_FAKE_BREAKOUT_GIVEBACK_RATIO",
    "DetectionTimingLabel",
    "OutcomeLabel",
    "PostDiscoveryCaptureStatus",
    "PostDiscoveryOutcomeForbiddenFieldError",
    "PricePoint",
    "HistoricalMoverReferenceSummary",
    "PostDiscoveryOutcomeInput",
    "PostDiscoveryOutcomeRecord",
    "PostDiscoveryOutcomeReport",
    "PostDiscoveryOutcomeEvaluatorConfig",
    "PostDiscoveryOutcomeEvaluator",
    "build_post_discovery_outcome_report",
    "assert_post_discovery_payload_has_no_forbidden_keys",
    # Phase 11C.1C-C-B-B-B-D-C-A Reject-to-Outcome Attribution v0
    "REJECT_TO_OUTCOME_ATTRIBUTION_VERSION",
    "REJECT_TO_OUTCOME_ATTRIBUTION_SOURCE_PHASE",
    "REJECT_TO_OUTCOME_ATTRIBUTION_SCHEMA_VERSION",
    "KNOWN_REJECT_TO_OUTCOME_ATTRIBUTION_SCHEMA_VERSIONS",
    "REJECT_ATTRIBUTION_FORBIDDEN_PAYLOAD_KEYS",
    "DEFAULT_FALSE_NEGATIVE_MFE_THRESHOLD",
    "DEFAULT_STRONG_REMAINING_UPSIDE_PCT",
    "RejectAttributionVerdict",
    "RejectAttributionForbiddenFieldError",
    "RejectAttributionInput",
    "RejectAttributionRecord",
    "RejectAttributionReport",
    "RejectAttributionEngineConfig",
    "RejectToOutcomeAttributionEngine",
    "build_reject_attribution_report",
    "assert_reject_attribution_payload_has_no_forbidden_keys",
    # Phase 11C.1C-C-B-B-B-D-C-B Severe Missed Tail Triage v0
    "SEVERE_MISSED_TAIL_TRIAGE_VERSION",
    "SEVERE_MISSED_TAIL_TRIAGE_SOURCE_PHASE",
    "SEVERE_MISSED_TAIL_TRIAGE_SCHEMA_VERSION",
    "KNOWN_SEVERE_MISSED_TAIL_TRIAGE_SCHEMA_VERSIONS",
    "SEVERE_MISSED_TAIL_TRIAGE_FORBIDDEN_PAYLOAD_KEYS",
    "DEFAULT_TRUE_DISCOVERY_FAILURE_MFE_THRESHOLD",
    "PROTECTIVE_REJECT_ATTRIBUTION_VERDICTS",
    "FALSE_NEGATIVE_REJECT_ATTRIBUTION_VERDICT",
    "STRATEGY_MODE_FALSE_NEGATIVE_VERDICT",
    "ROOT_CAUSE_DEFAULT_SEVERITY",
    "SevereMissRootCause",
    "SevereMissSeverity",
    "SevereMissedTailTriageForbiddenFieldError",
    "SevereMissTriageInput",
    "SevereMissTriageRecord",
    "SevereMissTriageReport",
    "SevereMissedTailTriageEngineConfig",
    "SevereMissedTailTriageEngine",
    "build_severe_missed_tail_triage_report",
    "assert_severe_missed_tail_triage_payload_has_no_forbidden_keys",
    # Phase 11C.1C-C-B-B-B-D-D Discovery Quality Scorecard v0
    "DISCOVERY_QUALITY_SCORECARD_VERSION",
    "DISCOVERY_QUALITY_SCORECARD_SOURCE_PHASE",
    "DISCOVERY_QUALITY_SCORECARD_SCHEMA_VERSION",
    "KNOWN_DISCOVERY_QUALITY_SCORECARD_SCHEMA_VERSIONS",
    "DISCOVERY_QUALITY_SCORECARD_FORBIDDEN_PAYLOAD_KEYS",
    "DEFAULT_GOOD_COVERAGE_RATE",
    "DEFAULT_PARTIAL_COVERAGE_RATE",
    "DEFAULT_GOOD_USABLE_DISCOVERY_RATE",
    "DEFAULT_PARTIAL_USABLE_DISCOVERY_RATE",
    "DEFAULT_SEVERE_MISS_RATE_WARN",
    "DEFAULT_SEVERE_MISS_RATE_DEGRADED",
    "DEFAULT_DATA_GAP_RATE_WARN",
    "DEFAULT_DATA_GAP_RATE_DEGRADED",
    "DEFAULT_INSUFFICIENT_PRICE_PATH_RATE_WARN",
    "DEFAULT_INSUFFICIENT_PRICE_PATH_RATE_DEGRADED",
    "DEFAULT_LATE_CHASE_RATE_WARN",
    "DEFAULT_FALSE_NEGATIVE_REJECT_RATE_WARN",
    "DiscoveryQualityBucket",
    "DiscoveryQualityScorecardForbiddenFieldError",
    "DiscoveryQualityScorecardInput",
    "DiscoveryQualityScorecard",
    "DiscoveryQualityScorecardEngineConfig",
    "DiscoveryQualityScorecardEngine",
    "build_discovery_quality_scorecard",
    "assert_discovery_quality_scorecard_payload_has_no_forbidden_keys",
    # Payload helpers
    "candidate_stage_assessment_to_payload",
    "cluster_context_to_payload",
    "label_queue_contract_to_payload",
    "market_regime_assessment_to_payload",
    "opportunity_score_to_payload",
    "runtime_calibration_metrics_to_payload",
    "strategy_mode_decision_to_payload",
    # Scoring helpers
    "OpportunityScoreInputs",
    "OpportunityScoreWeights",
    "DEFAULT_OPPORTUNITY_SCORE_WEIGHTS",
]
