"""OpportunityIdentity + helpers (Phase 8.5).

Issue contract:

    Each candidate opportunity must support:
      - opportunity_id     stable per-candidate identifier
      - scan_batch_id      identifier of the scan that produced it
      - symbol
      - first_seen_ts      ms timestamp of first detection
      - source_phase       which phase produced the candidate
                           (e.g. "pre_anomaly", "anomaly", "confirmation",
                           "manipulation", "regime", "universe", "risk_engine",
                           "state_machine", "capital", "scanner.full",
                           "phase_8_5_boot")

Both identifiers are deterministic UUID4 strings. The opportunity_id
is generated by ``make_opportunity_id()``; the scan_batch_id is
generated by ``make_scan_batch_id()``. Both helpers accept an
explicit value to support deterministic replay.

Phase 8.5 boundary
------------------

The identity object is a frozen Pydantic v2 model. It does NOT carry
PnL, position size, or any exchange-side identifier; those belong to
the future Issue #9 Execution FSM.
"""

from __future__ import annotations

import uuid
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from app.core.clock import now_ms

OPPORTUNITY_ID_PREFIX = "opp_"
SCAN_BATCH_ID_PREFIX = "scan_"


def make_opportunity_id(*, opportunity_id: str | None = None) -> str:
    """Return a deterministic opportunity identifier.

    Use the caller-supplied value when given; otherwise generate a
    fresh ``opp_<uuid4>`` string. The function never raises.
    """
    if opportunity_id is not None:
        return str(opportunity_id)
    return f"{OPPORTUNITY_ID_PREFIX}{uuid.uuid4().hex}"


def make_scan_batch_id(*, scan_batch_id: str | None = None) -> str:
    """Return a deterministic scan-batch identifier.

    A scan_batch_id groups every candidate produced by the same
    cross-market scan run, so future Replay / Dataset Builder /
    Reflection can group / count / split per batch.
    """
    if scan_batch_id is not None:
        return str(scan_batch_id)
    return f"{SCAN_BATCH_ID_PREFIX}{uuid.uuid4().hex}"


class OpportunityIdentity(BaseModel):
    """Identity object for one candidate opportunity.

    Frozen value object. Every field is JSON-safe so the object can be
    persisted directly in an event payload via
    :meth:`OpportunityIdentity.to_payload`.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    opportunity_id: str
    scan_batch_id: str
    symbol: str
    first_seen_ts: int = Field(default_factory=now_ms)
    source_phase: str

    # ------------------------------------------------------------------
    @classmethod
    def create(
        cls,
        *,
        symbol: str,
        source_phase: str,
        opportunity_id: str | None = None,
        scan_batch_id: str | None = None,
        first_seen_ts: int | None = None,
    ) -> "OpportunityIdentity":
        """Convenience factory that fills in the deterministic ids."""
        return cls(
            opportunity_id=make_opportunity_id(opportunity_id=opportunity_id),
            scan_batch_id=make_scan_batch_id(scan_batch_id=scan_batch_id),
            symbol=str(symbol),
            first_seen_ts=int(first_seen_ts) if first_seen_ts is not None else now_ms(),
            source_phase=str(source_phase),
        )

    def to_payload(self) -> dict[str, Any]:
        """Return a JSON-safe dict suitable for event payloads."""
        return {
            "opportunity_id": self.opportunity_id,
            "scan_batch_id": self.scan_batch_id,
            "symbol": self.symbol,
            "first_seen_ts": int(self.first_seen_ts),
            "source_phase": self.source_phase,
        }

    @classmethod
    def from_payload(cls, payload: dict[str, Any]) -> "OpportunityIdentity":
        """Inverse of :meth:`to_payload`. Strict on missing required keys."""
        return cls(
            opportunity_id=str(payload["opportunity_id"]),
            scan_batch_id=str(payload["scan_batch_id"]),
            symbol=str(payload["symbol"]),
            first_seen_ts=int(payload["first_seen_ts"]),
            source_phase=str(payload["source_phase"]),
        )
